name = "captcha-race"
compatibility_date = "2024-01-15"

[env.production]
name = "captcha-race"

[[env.production.kv_namespaces]]
binding = "LEADERBOARD"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# For Cloudflare Pages deployment
pages_build_output_dir = "dist"
